### PR TITLE
Simplify the main page to only guide the user in the right direction.

### PR DESCRIPTION
**Pull request by tjvantoll**
Ping @tralves @rigor789. Trying to simplify the main screen so the user sees something relatively simple to start with.

screen shot 2018-02-14 at 2 01 21 pm

### CODE REVIEW

**Comment by rigor789** [comment]
This was something that I wanted to do, as well as remove all the other samples included

**Comment by tjvantoll** [comment]
> as well as remove all the other samples included

@rigor789 You mean all the other app-* files? I’d be fine with that, but if we do that I think we need something to point the user at for a next step. I guess we could just tell people to check out the docs and that wouldn’t be so bad.

**Comment by rigor789** [comment]
Yeah I don't think having them in the template is really useful. If nothing else it's more confusing, because the user has to change the package.json to even see them.

**Comment by tjvantoll** [comment]
@rigor789 Agreed, but I’m in favor of leaving the files in there at least for the moment, just because we don’t have a lot of good samples up on the docs (yet).

**Pull request merged**
